=begin
#Wheel Fitment API

#The Wheel Fitment API allows for programmatic access to the database of www.wheel-size.com and its services. Use this API to retrieve information about vehicle fitment database for rims and tires, including OE and option fitments, and plus/minus sizing fitment information. A variety of country and language specific options are available. The coverage of fitment data for vehicles manufactured since 2000 is nearly 100%.  The information about fitment data is updated on a daily basis.

OpenAPI spec version: v1
Contact: info@wheel-size.com
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.0-SNAPSHOT

=end

require 'uri'

module WsApiClient
  class TrimsApi
    attr_accessor :api_client

    def initialize(api_client = ApiClient.default)
      @api_client = api_client
    end
    # Model modifications
    # List of model modifications matching given manufacturer, model and year
    # @param make Manufacturer slug name, use _**&#x60;GET /makes/&#x60;**_ to get possible values (e.g. &#x60;mitsubishi&#x60;)
    # @param model Model slug name, use _**&#x60;GET /models/&#x60;**_ to get possible values (e.g. &#x60;outlander&#x60;)
    # @param year You can use _**&#x60;GET /years/&#x60;**_ to get possible years (e.g. &#x60;2015&#x60;)
    # @param [Hash] opts the optional parameters
    # @return [Array<Trim>]
    def trims_list(make, model, year, opts = {})
      data, _status_code, _headers = trims_list_with_http_info(make, model, year, opts)
      data
    end

    # Model modifications
    # List of model modifications matching given manufacturer, model and year
    # @param make Manufacturer slug name, use _**&#x60;GET /makes/&#x60;**_ to get possible values (e.g. &#x60;mitsubishi&#x60;)
    # @param model Model slug name, use _**&#x60;GET /models/&#x60;**_ to get possible values (e.g. &#x60;outlander&#x60;)
    # @param year You can use _**&#x60;GET /years/&#x60;**_ to get possible years (e.g. &#x60;2015&#x60;)
    # @param [Hash] opts the optional parameters
    # @return [Array<(Array<Trim>, Fixnum, Hash)>] Array<Trim> data, response status code and response headers
    def trims_list_with_http_info(make, model, year, opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: TrimsApi.trims_list ...'
      end
      # verify the required parameter 'make' is set
      if @api_client.config.client_side_validation && make.nil?
        fail ArgumentError, "Missing the required parameter 'make' when calling TrimsApi.trims_list"
      end
      # verify the required parameter 'model' is set
      if @api_client.config.client_side_validation && model.nil?
        fail ArgumentError, "Missing the required parameter 'model' when calling TrimsApi.trims_list"
      end
      # verify the required parameter 'year' is set
      if @api_client.config.client_side_validation && year.nil?
        fail ArgumentError, "Missing the required parameter 'year' when calling TrimsApi.trims_list"
      end
      # resource path
      local_var_path = '/trims/'

      # query parameters
      query_params = {}
      query_params[:'make'] = make
      query_params[:'model'] = model
      query_params[:'year'] = year

      # header parameters
      header_params = {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json'])

      # form parameters
      form_params = {}

      # http body (model)
      post_body = nil
      auth_names = ['user_key']
      data, status_code, headers = @api_client.call_api(:GET, local_var_path,
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => 'Array<Trim>')
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: TrimsApi#trims_list\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end
  end
end
