=begin
#Wheel Fitment API

#The Wheel Fitment API allows for programmatic access to the database of www.wheel-size.com and its services. Use this API to retrieve information about vehicle fitment database for rims and tires, including OE and option fitments, and plus/minus sizing fitment information. A variety of country and language specific options are available. The coverage of fitment data for vehicles manufactured since 2000 is nearly 100%.  The information about fitment data is updated on a daily basis.

OpenAPI spec version: v1
Contact: info@wheel-size.com
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.0-SNAPSHOT

=end

require 'spec_helper'
require 'json'

# Unit tests for WsApiClient::YearsApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'YearsApi' do
  before do
    # run before each test
    @instance = WsApiClient::YearsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of YearsApi' do
    it 'should create an instance of YearsApi' do
      expect(@instance).to be_instance_of(WsApiClient::YearsApi)
    end
  end

  # unit tests for years_list
  # Returns list of years for the given manufacturer/model
  # Get a list of years that match the given manufacturer and model (if present)
  # @param make Manufacturer slug name, use _**&#x60;GET /makes/&#x60;**_ to get possible values (e.g. &#x60;mitsubishi&#x60;)
  # @param [Hash] opts the optional parameters
  # @option opts [String] :model Model slug name, use _**&#x60;GET /models/&#x60;**_ to get possible values (e.g. &#x60;outlander&#x60;)
  # @return [Array<Year>]
  describe 'years_list test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
