=begin
#Wheel Fitment API

#The Wheel Fitment API allows for programmatic access to the database of www.wheel-size.com and its services. Use this API to retrieve information about vehicle fitment database for rims and tires, including OE and option fitments, and plus/minus sizing fitment information. A variety of country and language specific options are available. The coverage of fitment data for vehicles manufactured since 2000 is nearly 100%.  The information about fitment data is updated on a daily basis.

OpenAPI spec version: v1
Contact: info@wheel-size.com
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.0-SNAPSHOT

=end

require 'uri'

module WsApiClient
  class YearsApi
    attr_accessor :api_client

    def initialize(api_client = ApiClient.default)
      @api_client = api_client
    end
    # Returns list of years for the given manufacturer/model
    # Get a list of years that match the given manufacturer and model (if present)
    # @param make Manufacturer slug name, use _**&#x60;GET /makes/&#x60;**_ to get possible values (e.g. &#x60;mitsubishi&#x60;)
    # @param [Hash] opts the optional parameters
    # @option opts [String] :model Model slug name, use _**&#x60;GET /models/&#x60;**_ to get possible values (e.g. &#x60;outlander&#x60;)
    # @return [Array<Year>]
    def years_list(make, opts = {})
      data, _status_code, _headers = years_list_with_http_info(make, opts)
      data
    end

    # Returns list of years for the given manufacturer/model
    # Get a list of years that match the given manufacturer and model (if present)
    # @param make Manufacturer slug name, use _**&#x60;GET /makes/&#x60;**_ to get possible values (e.g. &#x60;mitsubishi&#x60;)
    # @param [Hash] opts the optional parameters
    # @option opts [String] :model Model slug name, use _**&#x60;GET /models/&#x60;**_ to get possible values (e.g. &#x60;outlander&#x60;)
    # @return [Array<(Array<Year>, Fixnum, Hash)>] Array<Year> data, response status code and response headers
    def years_list_with_http_info(make, opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: YearsApi.years_list ...'
      end
      # verify the required parameter 'make' is set
      if @api_client.config.client_side_validation && make.nil?
        fail ArgumentError, "Missing the required parameter 'make' when calling YearsApi.years_list"
      end
      # resource path
      local_var_path = '/years/'

      # query parameters
      query_params = {}
      query_params[:'make'] = make
      query_params[:'model'] = opts[:'model'] if !opts[:'model'].nil?

      # header parameters
      header_params = {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json'])

      # form parameters
      form_params = {}

      # http body (model)
      post_body = nil
      auth_names = ['user_key']
      data, status_code, headers = @api_client.call_api(:GET, local_var_path,
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => 'Array<Year>')
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: YearsApi#years_list\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end
  end
end
